In [1]:
import pandas as pd

In [10]:
df1 = pd.read_csv("nba_salaries_&_stats2.csv")

df2 = pd.read_csv("height_weight.csv")

In [11]:
df2.rename(columns={'nombres': 'Player Name'}, inplace=True)

In [12]:
df2

    No.              Player Name Altura  Peso  Edad  Temporada Posicicion
0     1             Nikola Jokic  6'11"   254    29          9        Big
1     2    Giannis Antetokounmpo   7'0"   243    29         11        Big
2     3              Luka Doncic   6'7"   230    25          6      Guard
3     4  Shai Gilgeous-Alexander   6'6"   195    25          6      Guard
4     5              Joel Embiid   7'0"   280    30          8        Big
..  ...                      ...    ...   ...   ...        ...        ...
95   96             Terry Rozier   6'1"   190    30          9      Guard
96   97               Chris Paul   6'0"   175    38         19      Guard
97   98       Isaiah Hartenstein   7'0"   250    25          6        Big
98   99           Walker Kessler   7'1"   204    22          2        Big
99  100           Brandon Miller   6'9"   200    21          1    Forward

[100 rows x 7 columns]

In [13]:
df1

,Player Name,Salary,Position,Age,Team,PTS,Total Minutes,MP,FG%,3P%,FT%,TRB,AST,STL,BLK,TOV,PER
0,Stephen Curry,48070014,PG,34,GSW,29.4,1941,34.7,0.493,0.427,0.915,6.1,6.3,0.9,0.4,3.2,24.1
1,John Wall,47345760,PG,32,LAC,11.4,755,22.2,0.408,0.303,0.681,2.7,5.2,0.8,0.4,2.4,13.6
2,Russell Westbrook,47080179,PG,34,LAL/LAC,15.9,2126,29.1,0.436,0.311,0.656,5.8,7.5,1.0,0.5,3.5,16.1
3,LeBron James,44474988,PF,38,LAL,28.9,1954,35.5,0.500,0.321,0.768,8.3,6.8,0.9,0.6,3.2,23.9
4,Kevin Durant,44119845,PF,34,BRK/PHO,29.1,1672,35.6,0.560,0.404,0.919,6.7,5.0,0.7,1.4,3.3,25.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,Justin Minaya,35096,SF,23,POR,4.3,89,22.3,0.304,0.250,0.000,3.8,1.0,0.5,1.3,1.0,4.0
463,Kobi Simmons,32795,SG,25,CHO,1.0,28,5.6,0.167,0.200,1.000,0.8,1.0,0.0,0.4,0.2,9.0
464,Gabe York,32171,SG,29,IND,8.0,56,18.7,0.381,0.333,1.000,2.0,1.7,0.7,0.0,0.0,11.8
465,RaiQuan Gray,5849,PF,23,BRK,16.0,35,35.0,0.500,0.400,1.000,9.0,7.0,0.0,1.0,4.0,15.5
466,Jacob Gilyard,5849,PG,24,MEM,3.0,41,41.0,0.333,0.333,NaN,4.0,7.0,3.0,0.0,2.0,7.3

In [14]:
df3 = pd.merge(df1, df2, on='Player Name', how='inner')

In [15]:
%df3

,Player Name,Salary,Position,Age,Team,PTS,Total Minutes,MP,FG%,3P%,...,STL,BLK,TOV,PER,No.,Altura,Peso,Edad,Temporada,Posicicion
0,Stephen Curry,48070014,PG,34,GSW,29.4,1941,34.7,0.493,0.427,...,0.9,0.4,3.2,24.1,7,"6'3""",185,36,15,Guard
1,LeBron James,44474988,PF,38,LAL,28.9,1954,35.5,0.500,0.321,...,0.9,0.6,3.2,23.9,12,"6'9""",250,39,21,Forward
2,Kevin Durant,44119845,PF,34,BRK/PHO,29.1,1672,35.6,0.560,0.404,...,0.7,1.4,3.3,25.9,9,"6'10""",229,35,17,Forward
3,Bradley Beal,43279250,SG,29,WAS,23.2,1673,33.5,0.506,0.365,...,0.9,0.7,2.9,19.7,60,"6'4""",207,30,12,Guard
4,Kawhi Leonard,42492492,SF,31,LAC,23.8,1748,33.6,0.512,0.416,...,1.4,0.5,1.7,23.9,6,"6'7""",225,32,13,Forward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Immanuel Quickley,2316240,SG,23,NYK,14.9,2344,28.9,0.448,0.370,...,1.0,0.2,1.2,16.3,86,"6'3""",190,24,4,Guard
82,Jaden McDaniels,2161440,SF,22,MIN,12.1,2416,30.6,0.517,0.398,...,0.9,1.0,1.4,12.0,76,"6'9""",185,23,4,Forward
83,Desmond Bane,2130240,SG,24,MEM,21.5,1841,31.7,0.479,0.408,...,1.0,0.4,2.2,19.1,45,"6'5""",216,25,4,Guard
84,Naz Reid,1930681,C,23,MIN,11.5,1251,18.4,0.537,0.346,...,0.6,0.8,1.4,18.5,80,"6'9""",264,24,5,Big
85,Austin Reaves,1563518,SG,24,LAL,13.0,1843,28.8,0.529,0.398,...,0.5,0.3,1.5,14.9,77,"6'5""",206,25,3,Guard

In [16]:
f3 = ["Player Name","Salary","Position","Age","Team","PTS","Total Minutes","MP","FG%","3P%","FT%","TRB","AST","STL","BLK","TOV","TOV","PER","Altura","Peso"]

df4 = df3[f3]

In [17]:
df4

,Player Name,Salary,Position,Age,Team,PTS,Total Minutes,MP,FG%,3P%,FT%,TRB,AST,STL,BLK,TOV,TOV,PER,Altura,Peso
0,Stephen Curry,48070014,PG,34,GSW,29.4,1941,34.7,0.493,0.427,0.915,6.1,6.3,0.9,0.4,3.2,3.2,24.1,"6'3""",185
1,LeBron James,44474988,PF,38,LAL,28.9,1954,35.5,0.500,0.321,0.768,8.3,6.8,0.9,0.6,3.2,3.2,23.9,"6'9""",250
2,Kevin Durant,44119845,PF,34,BRK/PHO,29.1,1672,35.6,0.560,0.404,0.919,6.7,5.0,0.7,1.4,3.3,3.3,25.9,"6'10""",229
3,Bradley Beal,43279250,SG,29,WAS,23.2,1673,33.5,0.506,0.365,0.842,3.9,5.4,0.9,0.7,2.9,2.9,19.7,"6'4""",207
4,Kawhi Leonard,42492492,SF,31,LAC,23.8,1748,33.6,0.512,0.416,0.871,6.5,3.9,1.4,0.5,1.7,1.7,23.9,"6'7""",225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Immanuel Quickley,2316240,SG,23,NYK,14.9,2344,28.9,0.448,0.370,0.819,4.2,3.4,1.0,0.2,1.2,1.2,16.3,"6'3""",190
82,Jaden McDaniels,2161440,SF,22,MIN,12.1,2416,30.6,0.517,0.398,0.736,3.9,1.9,0.9,1.0,1.4,1.4,12.0,"6'9""",185
83,Desmond Bane,2130240,SG,24,MEM,21.5,1841,31.7,0.479,0.408,0.883,5.0,4.4,1.0,0.4,2.2,2.2,19.1,"6'5""",216
84,Naz Reid,1930681,C,23,MIN,11.5,1251,18.4,0.537,0.346,0.677,4.9,1.1,0.6,0.8,1.4,1.4,18.5,"6'9""",264
85,Austin Reaves,1563518,SG,24,LAL,13.0,1843,28.8,0.529,0.398,0.864,3.0,3.4,0.5,0.3,1.5,1.5,14.9,"6'5""",206

In [18]:
df4.to_csv('nba_salaries_&_stats3.csv', index=False)